// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stock_Pie.Infrastructure.Persistence;

#nullable disable

namespace Stock_Pie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610111520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoinWatchList", b =>
                {
                    b.Property<string>("CoinsId")
                        .HasColumnType("text");

                    b.Property<Guid>("WatchListsId")
                        .HasColumnType("uuid");

                    b.HasKey("CoinsId", "WatchListsId");

                    b.HasIndex("WatchListsId");

                    b.ToTable("CoinWatchList");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BuyPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("CoinId")
                        .HasColumnType("text");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.HasIndex("UserId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BuyPrice = 25000.0,
                            CoinId = "bitcoin",
                            Quantity = 0.5,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Coin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Ath")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AthChangePercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("AthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Atl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AtlChangePercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("AtlDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CirculatingSupply")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<long?>("FullyDilutedValuation")
                        .HasColumnType("bigint");

                    b.Property<decimal>("High24h")
                        .HasColumnType("numeric");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Low24h")
                        .HasColumnType("numeric");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("MarketCapChange24h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MarketCapChangePercentage24h")
                        .HasColumnType("numeric");

                    b.Property<int>("MarketCapRank")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxSupply")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("PriceChange24h")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceChangePercentage24h")
                        .HasColumnType("numeric");

                    b.Property<int?>("RoiId")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalSupply")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalVolume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RoiId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Id = "bitcoin",
                            Ath = 126080m,
                            AthChangePercentage = -40.0339m,
                            AthDate = new DateTime(2025, 10, 6, 18, 57, 42, 0, DateTimeKind.Utc),
                            Atl = 67.81m,
                            AtlChangePercentage = 111397.2809m,
                            AtlDate = new DateTime(2013, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CirculatingSupply = 20017090.0m,
                            CurrentPrice = 75605m,
                            FullyDilutedValuation = 1512981807039L,
                            High24h = 76134m,
                            Image = "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400",
                            LastUpdated = new DateTime(2026, 4, 17, 12, 10, 53, 0, DateTimeKind.Utc),
                            Low24h = 73501m,
                            MarketCap = 1512981807039L,
                            MarketCapChange24h = 19430849789m,
                            MarketCapChangePercentage24h = 1.30098m,
                            MarketCapRank = 1,
                            MaxSupply = 21000000.0m,
                            Name = "Bitcoin",
                            PriceChange24h = 859.52m,
                            PriceChangePercentage24h = 1.14992m,
                            Symbol = "btc",
                            TotalSupply = 20017090.0m,
                            TotalVolume = 42502155298m
                        },
                        new
                        {
                            Id = "ethereum",
                            Ath = 4891m,
                            AthChangePercentage = -17.7m,
                            AthDate = new DateTime(2021, 11, 10, 14, 24, 19, 0, DateTimeKind.Utc),
                            Atl = 0.43m,
                            AtlChangePercentage = 935000m,
                            AtlDate = new DateTime(2015, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CirculatingSupply = 120000000.0m,
                            CurrentPrice = 4025m,
                            FullyDilutedValuation = 483000000000L,
                            High24h = 4100m,
                            Image = "https://coin-images.coingecko.com/coins/images/279/large/ethereum.png",
                            LastUpdated = new DateTime(2026, 4, 17, 12, 10, 53, 0, DateTimeKind.Utc),
                            Low24h = 3900m,
                            MarketCap = 483000000000L,
                            MarketCapChange24h = 9500000000m,
                            MarketCapChangePercentage24h = 2.01m,
                            MarketCapRank = 2,
                            Name = "Ethereum",
                            PriceChange24h = 85.5m,
                            PriceChangePercentage24h = 2.17m,
                            Symbol = "eth",
                            TotalSupply = 120000000.0m,
                            TotalVolume = 21000000000m
                        },
                        new
                        {
                            Id = "tether",
                            Ath = 1.32m,
                            AthChangePercentage = -24.2m,
                            AthDate = new DateTime(2018, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Atl = 0.57m,
                            AtlChangePercentage = 75.4m,
                            AtlDate = new DateTime(2015, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CirculatingSupply = 102000000000.0m,
                            CurrentPrice = 1.00m,
                            FullyDilutedValuation = 102000000000L,
                            High24h = 1.01m,
                            Image = "https://coin-images.coingecko.com/coins/images/325/large/Tether.png",
                            LastUpdated = new DateTime(2026, 4, 17, 12, 10, 53, 0, DateTimeKind.Utc),
                            Low24h = 0.99m,
                            MarketCap = 102000000000L,
                            MarketCapChange24h = 500000000m,
                            MarketCapChangePercentage24h = 0.5m,
                            MarketCapRank = 3,
                            Name = "Tether",
                            PriceChange24h = 0.001m,
                            PriceChangePercentage24h = 0.1m,
                            Symbol = "usdt",
                            TotalSupply = 102000000000.0m,
                            TotalVolume = 60000000000m
                        },
                        new
                        {
                            Id = "binancecoin",
                            Ath = 690m,
                            AthChangePercentage = -10.1m,
                            AthDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Atl = 0.039m,
                            AtlChangePercentage = 1589000m,
                            AtlDate = new DateTime(2017, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CirculatingSupply = 153000000.0m,
                            CurrentPrice = 620m,
                            FullyDilutedValuation = 95000000000L,
                            High24h = 630m,
                            Image = "https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png",
                            LastUpdated = new DateTime(2026, 4, 17, 12, 10, 53, 0, DateTimeKind.Utc),
                            Low24h = 600m,
                            MarketCap = 95000000000L,
                            MarketCapChange24h = 1500000000m,
                            MarketCapChangePercentage24h = 1.6m,
                            MarketCapRank = 4,
                            MaxSupply = 200000000.0m,
                            Name = "BNB",
                            PriceChange24h = 12m,
                            PriceChangePercentage24h = 1.97m,
                            Symbol = "bnb",
                            TotalSupply = 153000000.0m,
                            TotalVolume = 1800000000m
                        });
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("BuyPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("CoinId")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<double>("SellPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentOrders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Amount = 49.99m,
                            PaymentMethod = 0,
                            Status = 0,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageBuyPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Symbol")
                        .IsUnique();

                    b.ToTable("Portfolios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AverageBuyPrice = 25000.00m,
                            LastUpdated = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "BTC",
                            TotalQuantity = 2.0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AverageBuyPrice = 140.00m,
                            LastUpdated = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Symbol = "AAPL",
                            TotalQuantity = 10.0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Roi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Times")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Roi");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PriceAtTransaction")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PriceAtTransaction = 20000m,
                            Quantity = 1.5m,
                            Symbol = "BTC",
                            TotalAmount = 30000m,
                            Type = 0,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PriceAtTransaction = 140m,
                            Quantity = 10m,
                            Symbol = "ETH",
                            TotalAmount = 1400m,
                            Type = 0,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailOtpExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailOtpHash")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            FullName = "Alice Doe",
                            IsActive = true,
                            PasswordHash = "$2a$12$0/Sr411KPa5E9ZmHWuovPOQM2hpRlLRWw1C8Hv2ps3x4wzWUYEo3q",
                            Provider = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@gmail.com",
                            FullName = "Bob Google",
                            IsActive = true,
                            PasswordHash = "$2a$12$0/Sr411KPa5E9ZmHWuovPOQM2hpRlLRWw1C8Hv2ps3x4wzWUYEo3q",
                            Provider = 1,
                            ProviderUserId = "google-123"
                        });
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Balance = 100000.0000m,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Balance = 50000.0000m,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Amount = 100000.0000m,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Initial deposit",
                            TransferId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Type = 0,
                            WalletId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Amount = 50000.0000m,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Initial deposit",
                            TransferId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Type = 0,
                            WalletId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.WatchList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("WatchLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Withdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("LocalDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Withdrawals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 2500.00m,
                            LocalDateTime = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("CoinWatchList", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.Coin", null)
                        .WithMany()
                        .HasForeignKey("CoinsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stock_Pie.Domain.Entities.WatchList", null)
                        .WithMany()
                        .HasForeignKey("WatchListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.Coin", "Coin")
                        .WithMany("Assets")
                        .HasForeignKey("CoinId");

                    b.HasOne("Stock_Pie.Domain.Entities.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Coin", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.Roi", "Roi")
                        .WithMany()
                        .HasForeignKey("RoiId");

                    b.Navigation("Roi");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Order", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId");

                    b.HasOne("Stock_Pie.Domain.Entities.Order", "Order")
                        .WithOne("OrderItem")
                        .HasForeignKey("Stock_Pie.Domain.Entities.OrderItem", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.PaymentOrder", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.User", "User")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Stock_Pie.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.WatchList", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.User", "User")
                        .WithOne("WatchList")
                        .HasForeignKey("Stock_Pie.Domain.Entities.WatchList", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Withdrawal", b =>
                {
                    b.HasOne("Stock_Pie.Domain.Entities.User", "User")
                        .WithMany("Withdrawals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Coin", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.User", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("PaymentOrders");

                    b.Navigation("Portfolios");

                    b.Navigation("Transactions");

                    b.Navigation("Wallet");

                    b.Navigation("WatchList");

                    b.Navigation("Withdrawals");
                });

            modelBuilder.Entity("Stock_Pie.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
